image: atlassian/default-image:2

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install shellcheck
          - find . -name "*.sh" -exec bash {} \;
          - find . -name "*.sh" -exec shellcheck {} \;