name: Bash CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
    - uses: actions/checkout@v2

    - name: Check for basic execution
      run: ls ./*.sh | xargs bash

    - name: Unit testing with bash_unit
      run: tests/bash_unit tests/test_*
