name: bash_unit CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
    - uses: actions/checkout@v2

    - name: Unit testing with bash_unit
      run: tests/bash_unit tests/test_*

  macos:
    runs-on: macos-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - uses: actions/checkout@v2

      - name: install gawk
        run: brew install gawk

      - name: Unit testing with bash_unit
        run: tests/bash_unit tests/test_*
